spring:
  application:
    name: soapUI-service
  datasource:
    url: jdbc:h2:file:~/.h2/soapUI;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    
server:
  port: 1112

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/